servo: Merge #11795 - Add pkg-config dep for ArchLinux (from ideasman42:patch-1); r=jdm
<!-- Please describe your changes on the following line: -->
Add pkg-config to readme.
---
<!-- Thank you for contributing to Servo! Please replace each `[ ]` by `[X]` when the step is complete, and replace `__` with appropriate data: -->
- [ ] `./mach build -d` does not report any errors
- [ ] `./mach test-tidy` does not report any errors
- [ ] These changes fix #__ (github issue number if applicable).

<!-- Either: -->
- [ ] There are tests for these changes OR
- [X] These changes do not require tests because this is an edit to the readme.

<!-- Pull requests that do not address these steps are welcome, but they will require additional verification as part of the review process. -->

Without this package, I get this error:

```
   Compiling servo-freetype-sys v2.4.11
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `dbus v0.3.3`
Process didn't exit successfully: `/dsk/src/servo/target/release/build/dbus-7f7af798babde0c1/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\"`: No such file or directory (os error 2)"', ../src/libcore/result.rs:785
note: Run with `RUST_BACKTRACE=1` for a backtrace.

[Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
Build completed in 0:05:27
```

Source-Repo: https://github.com/servo/servo
Source-Revision: 81ebde63319e3bf927655f8fa84500294152c122